### ISSUE TITLE
Quality of life suggestions

### ISSUE THREAD

**Issue by bathal1** [CGLab-GIST/target-aware-denoising#2]
Hi,

Thanks for sharing your implementation ! Overall I found it relatively easy to reproduce, thanks to the Docker setup, however I encountered a few minor annoyances that you might want to fix:

- `nvidia-docker` is obsolete and has been replaced by the NVIDIA Container Toolkit. Switching to that was pretty smooth on my end, the only change I had to add to the scripts was to change `nvidia-docker` to `docker`. You might want to update your scripts accordingly.
- On my machine, running docker requires sudo access. I expect this to be the default behavior in most cases.
- It's not clear from the README where the scenes folder should go. It is a bit tedious to have to guess from the error messages. 
- The scenes are not directly usable: one needs to rename the Ajar scene's `scene_v3.xml` to `scene.xml`, which is not obvious to someone with little Mitsuba experience, one needs to download another file for the intialisation of the sphere in the "curtain" scene (and it is again not clear where it should go and how it should be called). I would suggest that you provide a zip file with the scenes in the format expected by your code. 

Other than that, things were pretty smooth, and I could reproduce some results easily.

Best,
Baptiste

**Comment by JeongminGu** [comment]
Hi,

Thank you for the suggestions.
I'll provide the detailed instructions as your suggestions soon.

Best,
Jeonmin Gu.
