### ISSUE TITLE
Question on drjit backend about denoiser

### ISSUE THREAD

**Issue by jijiangli-swu-worker** [CGLab-GIST/target-aware-denoising#3]
Hi:
I try to use your offitical denoiser implementation in mitsuba, but the for rendering time cost without denoising to with denoising is from `0.61s` to `3.61s`, I think this caused by drjit to pytorch and convert it to drjit backend was high cost in time. So I'm here to ask would you have the plan to make the denoiser methods  like `Cross_Bilateral` or `simple_regression` to be pure coded in drjit backend, this will save time. If not, would you like to tell me the feasibility of my request, because I want to do it by myself, could it work as my wish? If yes, I will try in drjit coded version in my project.

**Comment by JeongminGu** [comment]
Hi,

I currently do not have plans to implement our denoiser in other versions. Additionally, you might consider exploring Drjit documentation and code examples to see if you can implement the denoisers yourself.

Best,
Jeongmin Gu
